### PR TITLE
Use the network.GetServiceHostname helper

### PR DESCRIPTION
**Pull request by mattmoor**
- 🧽 Update or clean up current behavior

### CODE REVIEW

**Review by n3wscott — COMMENTED** [review]
/lgtm
/approve

**Comment by mattmoor** [comment]
/retest

I would not expect alpha/beta variation, let's see if it repros

**Comment by mattmoor** [comment]
Ok it seems like it was a flake...

/assign @slinkydeveloper

**Comment by slinkydeveloper** [comment]
Seems fine to me

/lgtm
/approve

**Pull request merged**
