### PR TITLE
Backport of #433

### PR DESCRIPTION
**Pull request by devguyio**
## Proposed Changes

- Back porting #433 

**Release Note**

```release-note
A bug fix for the consolidated channel marking the subscription ready too early
```

### CODE REVIEW

**Comment by devguyio** [comment]
@lberk I cherry picked your dispatcher readiness commit. Mind blessing me with your `@googlebot I consent` :smile: 
@travis-minke-sap I cherry picked a fix commit you created for the distributed channel in this PR. Do you mind blessing me with your `@googlebot I consent`  :smile:

**Comment by devguyio** [comment]
@matzew the `pull-knative-sandbox-eventing-kafka-integration-test-mt-source` fails cause on 0.20 branch the e2e were not running the mtsource tests. It was added later here #350 . Do we need to cherry pick that as well?

**Comment by matzew** [comment]
@devguyio the third commit seems to break the `pull-knative-sandbox-eventing-kafka-build-tests`

I know that I can safely ignore the MT source case here :stuck_out_tongue_winking_eye: 

Thanks!

**Comment by devguyio** [comment]
@matzew fixed

**Comment by lberk** [comment]
@googlebot I consent

**Comment by travis-minke-sap** [comment]
@googlebot I consent

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

**Pull request merged**
