### PR TITLE
Activating HA scheduler for scaling and scheduling KafkaSource consumers

### PR DESCRIPTION
**Pull request by aavarghese**
Signed-off-by: aavarghese <avarghese@us.ibm.com>

Removing `MAXFILLUP` scheduling strategy and replacing with [Multi-Tenant HA Scheduler](https://github.com/knative/eventing/tree/main/pkg/scheduler)

### CODE REVIEW

**Comment by aavarghese** [comment]
```
{"level":"error","ts":"2022-04-05T17:13:05.634Z","logger":"kafka-controller.kafkabindings.webhook.kafka.sources.knative.dev","caller":"controller/controller.go:559","msg":"Reconcile error","knative.dev/traceid":"bc7029ab-6dc0-47f2-9b20-ce48c6bf5ece","knative.dev/key":"","duration":0.00010339,"error":"secret \"kafka-source-webhook-certs\" is missing \"ca-cert.pem\" key","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20220318185521-e6e3cf03d765/controller/controller.go:559\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20220318185521-e6e3cf03d765/controller/controller.go:536\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20220318185521-e6e3cf03d765/controller/controller.go:484"}
{"level":"debug","ts":"2022-04-05T17:13:05.634Z","logger":"kafka-controller.kafkabindings.webhook.kafka.sources.knative.dev","caller":"controller/controller.go:567","msg":"Requeuing key  due to non-permanent error (depth: 0)","knative.dev/traceid":"bc7029ab-6dc0-47f2-9b20-ce48c6bf5ece","knative.dev/key":""}
{"level":"warn","ts":"2022-04-05T17:13:05.953Z","logger":"kafka-controller","caller":"webhook/webhook.go:154","msg":"server key missing","stacktrace":"knative.dev/pkg/webhook.New.func2\n\tknative.dev/pkg@v0.0.0-20220318185521-e6e3cf03d765/webhook/webhook.go:154\ncrypto/tls.(*Config).getCertificate\n\tcrypto/tls/common.go:1042\ncrypto/tls.(*serverHandshakeStateTLS13).pickCertificate\n\tcrypto/tls/handshake_server_tls13.go:362\ncrypto/tls.(*serverHandshakeStateTLS13).handshake\n\tcrypto/tls/handshake_server_tls13.go:54\ncrypto/tls.(*Conn).serverHandshake\n\tcrypto/tls/handshake_server.go:54\ncrypto/tls.(*Conn).handshakeContext\n\tcrypto/tls/conn.go:1445\ncrypto/tls.(*Conn).HandshakeContext\n\tcrypto/tls/conn.go:1395\nnet/http.(*conn).serve\n\tnet/http/server.go:1817"}
2022/04/05 17:13:05 http: TLS handshake error from 10.73.188.58:37286: tls: no certificates configured
```

**Comment by lionelvillard** [comment]
/lgtm
/approve

the lint check fails due to this bug: https://github.com/golangci/golangci-lint/issues/2649

**Pull request merged**
