### PR TITLE
[0.25] KafkaChannel to init offsets before dispatcher 

### PR DESCRIPTION
**Pull request by aliok**
Manual cherry pick of the same fix in 0.24: https://github.com/knative-sandbox/eventing-kafka/pull/886

**Release Note**

```release-note
- 🐛  Fixed a bug that was causing Kafka Channel dispatcher to miss some events in case the offset for the consumer group was not initialized

```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
can we have this done via the bot? to make sure we exactly get all exactly same?

/hold

**Comment by matzew** [comment]
Or... use this `sha` https://github.com/knative-sandbox/eventing-kafka/commit/3f2a9d72d40d0d7afe5037ca45313c1de7723dd6

:pray:  Sorry I am a PITA here :smile_cat:

**Comment by aliok** [comment]
> can we have this done via the bot? to make sure we exactly get all exactly same?

There are conflicts.

**Comment by matzew** [comment]
ah....

ok

**Comment by aliok** [comment]
> Or... use this sha 3f2a9d7

But, that's a good point! I cherry picking a manually squashed commit to prepare this forward port in advance.
Let me rebase on to 3f2a9d7

> 🙏 Sorry I am a PITA here 😸
Nope you're not

**Comment by aliok** [comment]
/close

Closing in favor of https://github.com/knative-sandbox/eventing-kafka/pull/913

**Pull request closed without merging**
