### PR TITLE
Add label selector to enable HPA to scale Kafka source

### LINKED ISSUE #444: Unable to scale Kafka source with HPA
**Describe the bug**
Unable to scale single Kafka source with HPA

 **Expected behavior**
HAP should be able to scale Kafka source

 **To Reproduce**

Use HPA that is targeting Kafka source:

```
spec:
  scaleTargetRef:
    apiVersion: sources.knative.dev/v1beta1
    kind: KafkaSource
    name: kafka-src10
```

Problems:

```
 k describe hpa keda-hpa-so-96c230cf-052e-4243-a2d0-15fc80f8727f
Name:                                                      keda-hpa-so-96c230cf-052e-4243-a2d0-15fc80f8727f
Namespace:                                                 demo5
Labels:                                                    app.kubernetes.io/managed-by=keda-operator
                                                           app.kubernetes.io/name=keda-hpa-so-96c230cf-052e-4243-a2d0-15fc80f8727f
                                                           app.kubernetes.io/part-of=so-96c230cf-052e-4243-a2d0-15fc80f8727f
                                                           app.kubernetes.io/version=2.1.0
                                                           scaledObjectName=so-96c230cf-052e-4243-a2d0-15fc80f8727f
Annotations:                                               <none>
CreationTimestamp:                                         Tue, 09 Mar 2021 14:51:33 -0500
Reference:                                                 KafkaSource/kafka-src10
Metrics:                                                   ( current / target )
  "kafka-topic10-knative-group10" (target average value):  <unknown> / 2
Min replicas:                                              1
Max replicas:                                              50
KafkaSource pods:                                          2 current / 0 desired
Conditions:
  Type           Status  Reason             Message
  ----           ------  ------             -------
  AbleToScale    True    SucceededGetScale  the HPA controller was able to get the target's current scale
  ScalingActive  False   InvalidSelector    the HPA target's scale is missing a selector
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedComputeMetricsReplicas  20m (x41 over 30m)   horizontal-pod-autoscaler  selector is required
  Warning  SelectorRequired              37s (x121 over 30m)  horizontal-pod-autoscaler  selector is required
```

 **Knative release version**
0.21

 **Additional context**
Add any other context about the problem here such as proposed priority

Manual scaling of replcias works:
```
k scale kafkasources.sources.knative.dev kafka-src10 --replicas=2
kafkasource.sources.knative.dev/kafka-src10 scaled
```

### PR DESCRIPTION
**Pull request by aslom**
Fixes #

Fixes https://github.com/knative-sandbox/eventing-kafka/issues/444

## Proposed Changes

- add labelSelectorPath to CRDs
- add Status.Selector for all supported versions and conversions
- set Status.Selector with labels

**Release Note**

```release-note
- 🎁 HPA can be now used to scale Kafka source both single and multi-tenant. Details in https://github.com/knative-sandbox/eventing-kafka/issues/444
```

**Docs**

### CODE REVIEW

**Comment by aslom** [comment]
Tested Kafka source single: when traffic was generated and KEDA metrics provided HPA scaled Kafka source to 10 pods:

```
aslom@m:~/Documents/awsm/go/src/github.ibm.com/aslom/test-kafka-eventing|master⚡ ⇒  k describe hpa keda-hpa-so-9c85555e-dd62-48fb-bd78-2654b03045db
Name:                                                      keda-hpa-so-9c85555e-dd62-48fb-bd78-2654b03045db
Namespace:                                                 demo5
Labels:                                                    app.kubernetes.io/managed-by=keda-operator
                                                           app.kubernetes.io/name=keda-hpa-so-9c85555e-dd62-48fb-bd78-2654b03045db
                                                           app.kubernetes.io/part-of=so-9c85555e-dd62-48fb-bd78-2654b03045db
                                                           app.kubernetes.io/version=2.1.0
                                                           scaledObjectName=so-9c85555e-dd62-48fb-bd78-2654b03045db
Annotations:                                               <none>
CreationTimestamp:                                         Wed, 10 Mar 2021 10:19:25 -0500
Reference:                                                 KafkaSource/kafka-src10
Metrics:                                                   ( current / target )
  "kafka-topic10-knative-group10" (target average value):  2 / 2
Min replicas:                                              1
Max replicas:                                              50
KafkaSource pods:                                          10 current / 10 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric kafka-topic10-knative-group10(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: so-9c85555e-dd62-48fb-bd78-2654b03045db,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  SuccessfulRescale  70s   horizontal-pod-autoscaler  New size: 4; reason: external metric kafka-topic10-knative-group10(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: so-9c85555e-dd62-48fb-bd78-2654b03045db,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
  Normal  SuccessfulRescale  55s   horizontal-pod-autoscaler  New size: 8; reason: external metric kafka-topic10-knative-group10(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: so-9c85555e-dd62-48fb-bd78-2654b03045db,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
  Normal  SuccessfulRescale  40s   horizontal-pod-autoscaler  New size: 10; reason: external metric kafka-topic10-knative-group10(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: so-9c85555e-dd62-48fb-bd78-2654b03045db,},MatchExpressions:[]LabelSelectorRequirement{},}) above target
```

```
aslom@m:~/Documents/awsm/go/src/github.ibm.com/aslom/test-kafka-eventing|master⚡ ⇒  k get po
NAME                                                              READY   STATUS      RESTARTS   AGE
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b0304579lmf   1/1     Running     0          76s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045bb5h8   1/1     Running     0          61s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045fj7j6   1/1     Running     0          46s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045g5dwv   1/1     Running     0          6m49s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045hsljt   1/1     Running     0          76s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045jl5br   1/1     Running     0          46s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045l2pxw   1/1     Running     0          61s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045mjhgv   1/1     Running     0          61s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045mw7hc   1/1     Running     0          76s
kafkasource-kafka-src10-9c85555e-dd62-48fb-bd78-2654b03045t2vsg   1/1     Running     0          61s
```

**Comment by aslom** [comment]
When Kafka source multi we redeployed (make sure to delete single frst):

```
ko delete -f config/source/single
ko apply -f config/source/multi
```

HPA was able to scale:

```
 k describe hpa keda-hpa-so-80a95895-0816-4438-81f3-a19e30fcf1f3
Name:                                                      keda-hpa-so-80a95895-0816-4438-81f3-a19e30fcf1f3
Namespace:                                                 demo5
Labels:                                                    app.kubernetes.io/managed-by=keda-operator
                                                           app.kubernetes.io/name=keda-hpa-so-80a95895-0816-4438-81f3-a19e30fcf1f3
                                                           app.kubernetes.io/part-of=so-80a95895-0816-4438-81f3-a19e30fcf1f3
                                                           app.kubernetes.io/version=2.1.0
                                                           scaledObjectName=so-80a95895-0816-4438-81f3-a19e30fcf1f3
Annotations:                                               <none>
CreationTimestamp:                                         Wed, 10 Mar 2021 10:30:03 -0500
Reference:                                                 KafkaSource/kafka-src10
Metrics:                                                   ( current / target )
  "kafka-topic10-knative-group10" (target average value):  -9223372036854775808m / 2
Min replicas:                                              1
Max replicas:                                              50
KafkaSource pods:                                          10 current / 10 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric kafka-topic10-knative-group10(&LabelSelector{MatchLabels:map[string]string{scaledObjectName: so-80a95895-0816-4438-81f3-a19e30fcf1f3,},MatchExpressions:[]LabelSelectorRequirement{},})
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:           <none>
```

And number of vreplicas increased to multi Kafka source

```
placements:
  - podName: kafkasource-mt-adapter-0
    vreplicas: 10
```

in

```
k get kafkasources.sources.knative.dev kafka-src10 -oyaml
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  annotations:
    autoscaling.knative.dev/class: keda.autoscaling.knative.dev
    autoscaling.knative.dev/maxScale: "50"
    autoscaling.knative.dev/minScale: "1"
    keda.autoscaling.knative.dev/cooldownPeriod: "10"
    keda.autoscaling.knative.dev/kafkaLagThreshold: "2"
    keda.autoscaling.knative.dev/pollingInterval: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sources.knative.dev/v1beta1","kind":"KafkaSource","metadata":{"annotations":{"autoscaling.knative.dev/class":"keda.autoscaling.knative.dev","autoscaling.knative.dev/maxScale":"50","autoscaling.knative.dev/minScale":"1","keda.autoscaling.knative.dev/cooldownPeriod":"10","keda.autoscaling.knative.dev/kafkaLagThreshold":"2","keda.autoscaling.knative.dev/pollingInterval":"10"},"name":"kafka-src10","namespace":"demo5"},"spec":{"bootstrapServers":["my-cluster-kafka-bootstrap.kafka:9092"],"consumerGroup":"knative-group10","consumers":1,"sink":{"ref":{"apiVersion":"v1","kind":"Service","name":"receiver"}},"topics":["topic10"]}}
  creationTimestamp: "2021-03-10T15:30:03Z"
  generation: 4
  managedFields:
  - apiVersion: sources.knative.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:autoscaling.knative.dev/class: {}
          f:autoscaling.knative.dev/maxScale: {}
          f:autoscaling.knative.dev/minScale: {}
          f:keda.autoscaling.knative.dev/cooldownPeriod: {}
          f:keda.autoscaling.knative.dev/kafkaLagThreshold: {}
          f:keda.autoscaling.knative.dev/pollingInterval: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:bootstrapServers: {}
        f:consumerGroup: {}
        f:consumers: {}
        f:sink:
          .: {}
          f:ref:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
        f:topics: {}
    manager: kubectl
    operation: Update
    time: "2021-03-10T15:30:03Z"
  - apiVersion: sources.knative.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:ceAttributes: {}
        f:conditions: {}
        f:observedGeneration: {}
        f:placements: {}
        f:selector: {}
        f:sinkUri: {}
    manager: mtcontroller
    operation: Update
    time: "2021-03-10T15:30:03Z"
  name: kafka-src10
  namespace: demo5
  resourceVersion: "7107279"
  selfLink: /apis/sources.knative.dev/v1beta1/namespaces/demo5/kafkasources/kafka-src10
  uid: 80a95895-0816-4438-81f3-a19e30fcf1f3
spec:
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  consumerGroup: knative-group10
  consumers: 10
  net:
    sasl:
      password: {}
      type: {}
      user: {}
    tls:
      caCert: {}
      cert: {}
      key: {}
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: receiver
  topics:
  - topic10
status:
  ceAttributes:
  - source: /apis/v1/namespaces/demo5/kafkasources/kafka-src10#topic10
    type: dev.knative.kafka.event
  conditions:
  - lastTransitionTime: "2021-03-10T15:30:03Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2021-03-10T15:30:03Z"
    status: "True"
    type: Scheduled
  - lastTransitionTime: "2021-03-10T15:30:03Z"
    status: "True"
    type: SinkProvided
  observedGeneration: 4
  placements:
  - podName: kafkasource-mt-adapter-0
    vreplicas: 10
  selector: control-plane=kafkasource-mt-adapter
  sinkUri: http://receiver.demo5.svc.cluster.local/
```

**Review by lionelvillard — APPROVED** [review]

**Review by steven0711dong — APPROVED** [review]
LGTM

**Comment by lionelvillard** [comment]
Closing to see if it unblock #454 

Will reopen...

**Comment by aslom** [comment]
Closing to get bot "cla/google Expected — Waiting for status to be reported" to re-evaluate?

**Pull request closed without merging**
