### PR TITLE
Convert to go mod

### LINKED ISSUE #6: Convert to Go Mod
Get rid of dep and switch over! Lots of examples in eventing and eventing-contrib to reference here.

### PR DESCRIPTION
**Pull request by davyodom**
Fixes #6 
Converting to go mod.

### CODE REVIEW

**Comment by davyodom** [comment]
/hold
I want to get the release build merged first before merging this in, as it will be easier to rebase this one on top instead of the other way around

**Comment by davyodom** [comment]
latest dependency upgrade was done to get new things required from test-infra, but new pkg that got pulled in had some breaking changes.  Fix is coming shortly

**Comment by travis-minke-sap** [comment]
lgtm - I've built/run this branch successfully as well !

**Comment by davyodom** [comment]
more breakage from having to upgrade dependencies than expected.  I'll kill this PR and create a new one after all of those changes are resolved
/close

**Pull request closed without merging**
