### PR TITLE
Align our test Kafka cluster with the defaults from upstream strimzi

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

- as on the upstream samples, for better test reliability (see: https://github.com/strimzi/strimzi-kafka-operator/commit/45a56c41d7c2fa71b225851a28fafe29eb300511#diff-126b1b3c84d8709e68f4ed91189dc23542bd3be8852cf369c8c52c8e5e9fc6fdR22-R23) 

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by aliok** [comment]
cc @travis-minke-sap

**Comment by matzew** [comment]
looks like this causes problems

**Pull request closed without merging**
