### PR TITLE
Go w/ Sarama 1.29.0

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

- updating to recent version of the kafka client

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by slinkydeveloper — DISMISSED** [review]
No breaking changes, I guess we're good https://github.com/Shopify/sarama/releases/tag/v1.29.0

/lgtm

**Comment by slinkydeveloper** [comment]
There's a change in the test string assertion :)

**Comment by travis-minke-sap** [comment]
thanks for moving us forward - once the tests pass it's fine with us - thanks!
/lgtm

**Comment by travis-minke-sap** [comment]
To fix the failing test just change line 27 in `pkg/channel/distributed/common/kafka/admin/util/util.go` from...
```
maxKError = sarama.ErrFencedInstancedId
```
to
```
maxKError = sarama. ErrUnstableOffsetCommit
```

sorry for the semi-brittle implementation - we're mapping Sarama errors and are using the range of valid values.  In a way it's a good thing the test broke as it notified us to make the change.

**Comment by matzew** [comment]
there is one more w/ the mock libary.

will look next week :smile:

**Comment by travis-minke-sap** [comment]
Pretty sure adding the following to line 339 of `pkg/channel/distributed/common/kafka/admin/kafka/adminclient_test.go` will fix the distributed failure...

```
func (m *MockClusterAdmin) DescribeUserScramCredentials(users []string) ([]*sarama.DescribeUserScramCredentialsResult, error) {
	panic("implement me")
}

func (m *MockClusterAdmin) DeleteUserScramCredentials(delete []sarama.AlterUserScramCredentialsDelete) ([]*sarama.AlterUserScramCredentialsResult, error) {
	panic("implement me")
}

func (m *MockClusterAdmin) UpsertUserScramCredentials(upsert []sarama.AlterUserScramCredentialsUpsert) ([]*sarama.AlterUserScramCredentialsResult, error) {
	panic("implement me")
}
```

and I'm assuming the same or similar is true for `pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go` as well.    Thanks again!

**Pull request merged**
