### PR TITLE
Remove deprecated test

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

## Proposed Changes

- Removing a depracted test, as part of cleaning up the `eventing/core` tests/helpers that are deprecated

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by creydr — APPROVED** [review]
/lgtm

**Review by creydr — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
:heart:

**Pull request merged**
