### PR TITLE
Remove transformevents and sequencestepper

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Updates eventing and removes transformevents and sequencestepper imported images

Also contains a fix for the monitoring removal

Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Look at https://github.com/knative/eventing/pull/4309 for more details

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@matzew is it normal that unit and build test fails? these failures doesn't seem related to my changes

**Comment by pierDipi** [comment]
@slinkydeveloper The monitoring bits are also here https://github.com/knative-sandbox/eventing-kafka/pull/113

**Comment by slinkydeveloper** [comment]
seems like @matzew beat me on time, what of the two we wanna merge?

**Comment by matzew** [comment]
@slinkydeveloper we take yours :-)

**Pull request merged**
