### PR TITLE
fix custom consumer group error channel lifecycle

### LINKED ISSUE #174: KafkaSource dispatcher crashes when sink is deleted (and session closed?)
**Describe the bug**

Getting this error:

```
{"level":"debug","ts":"2020-11-06T21:37:51.590Z","caller":"adapter/adapter.go:136","msg":"Error while sending the message{error 26 0  Post \"http://event-display.sources-kafka-keda.svc.cluster.local/\": dial tcp 10.96.140.159:80: connect: connection refused}"}
{"level":"info","ts":"2020-11-06T21:37:51.590Z","caller":"consumer/consumer_handler.go:83","msg":"Failure while handling a message","topic":"products","partition":7,"offset":14373,"error":"Post \"http://event-display.sources-kafka-keda.svc.cluster.local/\": dial tcp 10.96.140.159:80: connect: connection refused"}
panic: send on closed channel

goroutine 349 [running]:
knative.dev/eventing-kafka/pkg/common/consumer.(*SaramaConsumerHandler).ConsumeClaim(0xc000706480, 0x20eb100, 0xc0007a9c00, 0x20dd6a0, 0xc000a3ef30, 0x8, 0x7)
        knative.dev/eventing-kafka/pkg/common/consumer/consumer_handler.go:84 +0xbf3
github.com/Shopify/sarama.(*consumerGroupSession).consume(0xc0007a9c00, 0xc0008601f0, 0x8, 0x7)
        github.com/Shopify/sarama@v1.27.0/consumer_group.go:690 +0x27f
github.com/Shopify/sarama.newConsumerGroupSession.func2(0xc0007a9c00, 0xc0008601f0, 0x8, 0xc000000007)
        github.com/Shopify/sarama@v1.27.0/consumer_group.go:615 +0x87
created by github.com/Shopify/sarama.newConsumerGroupSession
        github.com/Shopify/sarama@v1.27.0/consumer_group.go:607 +0x526
```

 **Expected behavior**

no crash

 **To Reproduce**
Steps to reproduce the behavior.

TDB. In a nutshell, create a KafkaSource, scale it to few pods, kill the sink and observe the crash. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by lionelvillard**
Fixes #174

## Proposed Changes

- Scope consumer group handler to a session. 
- Scope error channel to a consumer group 
-

**Release Note**

```release-note
🐛 Fix crash in Kafka consumer when a rebalance occurs
```

**Docs**

### CODE REVIEW

**Comment by lberk** [comment]
awesome! thanks for putting this together. Given the nature of the crash -- is there any way we could add an e2e test to make sure we catch this moving forward? Delete the sink during a session?

**Comment by lionelvillard** [comment]
I still need to find a good way to test this. The problem with deleting the sink is it takes 4-5mn for the buffer to be depleted (not sure exactly why). 

The way to reproduce is:
1. send events to a broken sink
2. trigger a rebalance by changing the number of replicas on the adapter
3. wait a bit for ConsumerHandler to Cleanup
4. a new consumer handler is created (no crash)

**Pull request merged**
