### PR TITLE
Update to latest eventing deps

### PR DESCRIPTION
**Pull request by skonto**
Update due to https://github.com/knative/eventing/pull/5505

### CODE REVIEW

**Comment by lionelvillard** [comment]
@skonto can you fix the `goimports` failure? Also running `hack/update-deps.sh --upgrade` should fix the Verify job.

**Comment by skonto** [comment]
If I run `hack/update-deps.sh --upgrade` a lot of unrelated stuff are upgraded should they?
Eg. `go get: upgraded go.uber.org/atomic v1.7.0 => v1.8.0`

**Comment by skonto** [comment]
The lint issue seems a false positive to me.

**Comment by skonto** [comment]
@lionelvillard anythign more I can do here?

**Comment by lionelvillard** [comment]
> The lint issue seems a false positive to me.

It's not but all not related to this PR. Strange.. 

/lgtm
/approve

**Comment by skonto** [comment]
Let me do another round of updates as I got https://github.com/knative/eventing/pull/5512 in.
/hold

**Comment by skonto** [comment]
closing this in favor of https://github.com/knative-sandbox/eventing-kafka/pull/713

**Pull request closed without merging**
