### PR TITLE
Remove sleep and wait for KafkaSource reconciliation

### PR DESCRIPTION
**Pull request by pierDipi**
The sleep is causing flaky tests in eventing-kafka-broker and
in this repository (as the skip suggests)

Fixes a TODO

## Proposed Changes

- Remove sleep and wait for KafkaSource reconciliation

**Release Note**

```release-note
None
```

**Docs**

```
None
```

### CODE REVIEW

**Comment by pierDipi** [comment]
Worked, retesting
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-consolidated

**Comment by pierDipi** [comment]
2/2 Worked, retesting
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-consolidated

**Comment by pierDipi** [comment]
(Upgrade test is broker even without this changes)

**Review by odacremolbap — APPROVED** [review]
not an approver but +1 🙂

**Pull request merged**
