### PR TITLE
Try to get kafka in contained

### PR DESCRIPTION
**Pull request by matzew**
Getting kafka, via a "contrib" container

### CODE REVIEW

**Comment by aliok** [comment]
CLA consent will be a PITA this way unless somebody overrides that.

**Comment by matzew** [comment]
@grantr @mattmoor   as discussed on Friday, via slack.

The motivation here for this PR is, that moving the kafka bits to an _exisiting_ (non-empty) repo makes it hard to keep the history.

We are now importing the kafka source code via the `contrib` folder, in order to preserve the commit history.

So we need two things:

* google to manually approve the CLA thing, since we are _just_ importing from a different knative repo
* unblock this PR as in testing etc

Thanks for helping!!

**Comment by grantr** [comment]
Manually flipping CLA to yes. This is a move of code from an existing repo and was approved by the CLA when previously merged.

Approved by `xam@`/@sillsm

**Comment by matzew** [comment]
@grantr @mattmoor 

Let's do a merge commit ....   with that, we do:

* loose the actual file history (see: https://github.com/matzew/eventing-kafka/commits/test_merge_commit/contrib/kafka/source)
* KEEP the git-blame (see: https://github.com/matzew/eventing-kafka/blame/test_merge_commit/contrib/kafka/source/cmd/controller/main.go)
* KEEP the actual commits as well (see: https://github.com/matzew/eventing-kafka/commit/f353ce3b25097a76cf7f8295ffd384b42a345ec4)


/cc @slinkydeveloper

**Comment by slinkydeveloper** [comment]
Agree with @matzew, we're doing this to keep the commit history, so let's avoid the merge. For me it's a green flag, @travis-minke-sap are you ok with this?

/lgtm
/hold

**Comment by travis-minke-sap** [comment]
> Agree with @matzew, we're doing this to keep the commit history, so let's avoid the merge. For me it's a green flag, @travis-minke-sap are you ok with this?

👍  I'm ok with whatever approach you guys want to take regarding the history of the eventing-contrib/kafka source.

**Comment by mattmoor** [comment]
@grantr @thisisnotapril This needs a Googler

**Pull request merged**
