### PR TITLE
Delete v1alpha1 for source and bindings

### LINKED ISSUE #66: Remove KafkaSource v1alpha1 API shape
Remove KafkaSource and KafkaBinding v1alpha1 API shape as written here: https://github.com/knative/eventing-contrib/pull/1504#pullrequestreview-474244750

Part of umbrella issue, https://github.com/knative-sandbox/eventing-kafka/issues/65

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #66

## Proposed Changes

- :wastebasket: Remove KafkaBinding v1alpha1
- :wastebasket: Remove KafkaSource v1alpha1

**Release Note**

```release-note
🗑️ Remove KafkaBinding v1alpha1
🗑️ Remove KafkaSource v1alpha1
```

**Docs**

### CODE REVIEW

**Review by slinkydeveloper — COMMENTED** [review]
So we're not providing any transition path between v1alpha1 and v1beta1?

**Comment by matzew** [comment]
> So we're not providing any transition path between v1alpha1 and v1beta1?

ah, I will add the migration thingy - yes, forgot about. will update the PR

/hold

**Comment by matzew** [comment]
@slinkydeveloper we have this already there:
https://github.com/knative-sandbox/eventing-kafka/tree/main/config/post-install

**Review by slinkydeveloper — DISMISSED** [review]
/lgtm

/hold
better to have another pair of eyes on it

**Review by lionelvillard — APPROVED** [review]

**Pull request merged**
