### PR TITLE
[Consolidated Channel] Revert "Dispatcher readiness e2e test (#476)"

### PR DESCRIPTION
**Pull request by devguyio**
This reverts commit dcbe68cc1b0625fa16572097cc421ba3267e248f.

We see a lot of flakiness in consolidated channel e2e tests and this test might be the reason cause the tests aren't ready for scaling the deployment during the execution. 

We still need to investigate more though and reintroduce this test after fixing the root cause.

### CODE REVIEW

**Comment by devguyio** [comment]
Gonna unhold when it's clear this fixes the flakes
/hold

**Comment by lberk** [comment]
instead of outright reverting the change -- could we just `t.Skip()` it for now?

**Comment by devguyio** [comment]
@lberk why do you think we should skip instead of reverting? are there specific reasons?

**Comment by devguyio** [comment]
@lberk I had a change of heart trying to think which approach to weigh in for. I'm leaning more towards skipping to keep the test in mind and make it handy  to enable it locally whenever someone starts working on fixing the real root cause of the flakiness.

I'll close this and introduce another PR.

**Pull request closed without merging**
