### PR TITLE
Update to latest eventing deps

### PR DESCRIPTION
**Pull request by skonto**
## Proposed Changes

- Adding latest eventing deps 
- Needed for #688 

/cc @matzew

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by skonto** [comment]
> Reason:FailedMount
        Message:MountVolume.SetUp failed for volume "e2e-kafka-r-binary-plain-v1beta1-token-s729t" : failed to sync secret cache: timed out waiting for the condition

Seems irrelevant.

**Pull request merged**
