### PR TITLE
Update to latest eventing

### PR DESCRIPTION
**Pull request by slinkydeveloper**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
Links to https://github.com/cloudevents/sdk-go/pull/675

**Comment by slinkydeveloper** [comment]
I tested with the patch https://github.com/cloudevents/sdk-go/pull/675 locally and it works

**Comment by matzew** [comment]
@slinkydeveloper there is still an issue w/ the e2e tests for this

**Review by matzew — CHANGES_REQUESTED** [review]
can you adjust to 2.4.1 release of the cloudevents sdk ?

**Comment by slinkydeveloper** [comment]
The lint failure is not related to this PR, i would prefer to avoid fixing it here

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
