### PR TITLE
fix codeowners for the mtsource code

### PR DESCRIPTION
**Pull request by lionelvillard**

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
hm, this doesn't get merged automatically. Should I merge using the button? BTW, it wasn't enabled previously :)

**Comment by matzew** [comment]
I don't get this .... why is it not automatically merged ?

**Comment by lionelvillard** [comment]
I wonder if this is because Tide is looping on #453 (see https://prow.knative.dev/tide-history). I'm going to close #453 and see...

**Comment by lionelvillard** [comment]
that was it. :-)

**Pull request merged**
