### PR TITLE
[release-1.0] Consumer manager use factory merged errors (#1044)

### PR DESCRIPTION
**Pull request by eric-sap**
* ConsumerGroup Manager-use factory merged errors channel (fix for #1043)

This is a cherry-pick of #1044

### CODE REVIEW

**Comment by eric-sap** [comment]
The pull-knative-sandbox-eventing-kafka-upgrade-tests looks like it's having difficulty installing v0.27.0 ?  I'm not sure if that's because 0.27 became 1.0 ?

**Comment by pierDipi** [comment]
@eric-sap I think we need to upgrade knative.dev/hack, `go get -u knative.dev/hack@release-1.0 && hack/update-codegen.sh`

**Comment by eric-sap** [comment]
I believe that update did the trick; thank you very much!

**Pull request merged**
