### PR TITLE
Deprecate components

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

## Proposed Changes

- Adding note that some components in repo are no longer maintained.

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by pierDipi** [comment]
Can we remove them from the released YAMLs: https://github.com/knative-sandbox/eventing-kafka/blob/07af4e8e1ee3e5469b94073bc497b2619c310650/hack/release.sh#L26-L34

**Comment by pierDipi** [comment]
Related discussion: https://knative.slack.com/archives/C9JP909F0/p1667841421355339

**Comment by dprotaso** [comment]
If the components are specific to certain packages you can probably mark those packages are deprecated using godoc

https://go.dev/blog/godoc

**Comment by creydr** [comment]
> Can we remove them from the released YAMLs:
> 
> https://github.com/knative-sandbox/eventing-kafka/blob/07af4e8e1ee3e5469b94073bc497b2619c310650/hack/release.sh#L26-L34

Should we continue on this? We have some CI upgrade test failures, as it uses some deprecated API version for PodDisruptionBudget and HPA (see #1287 for example). Or would we first have to deprecate but keep them in the yamls for a few releases?

**Comment by pierDipi** [comment]
@creydr yes, please, we cannot move forward with the release (yesterday) without this

**Comment by pierDipi** [comment]
See https://github.com/knative-sandbox/eventing-kafka/pull/1327

**Pull request closed without merging**
