### PR TITLE
Idempotent Kafka secret creation in e2e tests

### PR DESCRIPTION
**Pull request by aliok**
Fixes #

## Proposed Changes

- Idempotent Kafka secret creation in e2e tests
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by aliok** [comment]
/hold

Need https://github.com/knative-sandbox/eventing-kafka/pull/1278 first

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by aliok** [comment]
/close

Can't merge

**Pull request closed without merging**
