### PR TITLE
Fix distributed multi cert tests

### PR DESCRIPTION
**Pull request by eric-sap**
This change is only to the TestExtractRootCerts function as I needed the multi-cert functionality and wanted it to be testable. 

## Proposed Changes

- 🧽  Update TestExtractRootCerts test to include multiple certificates

### CODE REVIEW

**Comment by travis-minke-sap** [comment]
typos... 🤦 
/ok-to-test

**Comment by travis-minke-sap** [comment]
> @travis-minke-sap we migrated to use [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) for approval.

Hey Lionel - thanks - I'm not sure what's amiss though - As far as I can tell I'm a member of that team...
https://github.com/orgs/knative-sandbox/teams/eventing-kafka-approvers/members

Any ideas?

**Comment by pierDipi** [comment]
It only works with GH approval

image

**Comment by travis-minke-sap** [comment]
oh - doh - sorry - missed that connection ; ).  THANK YOU !

**Review by travis-minke-sap — APPROVED** [review]
no more /lgtm ; )

**Pull request merged**
