### PR TITLE
Expand number of kafkasource fields that are now mutable, add e2e tests

### PR DESCRIPTION
**Pull request by lberk**
## Proposed Changes
- 🧽 Update or clean up current behavior

**Release Note**

```release-note
The kafkasource now allows for mutable fields for:
- Topics 
- BootstrapServers 
- Sink
- Net
- CloudEventOverrides
Previously, after creation, all fields were immutable.
```

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

/hold 
(for e2e test)

**Comment by lberk** [comment]
@lionelvillard it looks like the infra for the mtsource is broken? am I reading that correctly with the kill output? any pointers

**Comment by lionelvillard** [comment]
@lberk please ignore. It is flaky.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
