### PR TITLE
make space for mt source

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

- Make space for the multi-tenant source
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by steven0711dong — APPROVED** [review]
LGTM

**Review by pierDipi — APPROVED** [review]
/lgtm

**Comment by pierDipi** [comment]
GH action verify deps failed with:
```
Run curl -L https://github.com/google/ko/releases/download/v0.6.0/ko_0.6.0_Linux_x86_64.tar.gz | tar xzf - ko
  curl -L https://github.com/google/ko/releases/download/v0.6.0/ko_0.6.0_Linux_x86_64.tar.gz | tar xzf - ko
  chmod +x ./ko
  sudo mv ko /usr/local/bin
  go get github.com/google/go-licenses
  shell: /bin/bash -e {0}
  env:
    GOPATH: /home/runner/work/eventing-kafka/eventing-kafka
    GOROOT: /opt/hostedtoolcache/go/1.15.6/x64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   654  100   654    0     0   3027      0 --:--:-- --:--:-- --:--:--  3027

  0 10.8M    0 33344    0     0  53780      0  0:03:32 --:--:--  0:03:32 53780
100 10.8M  100 10.8M    0     0  7818k      0  0:00:01  0:00:01 --:--:-- 13.4M
# cd .; git clone -- https://gopkg.in/src-d/go-billy.v4 /home/runner/work/eventing-kafka/eventing-kafka/src/gopkg.in/src-d/go-billy.v4
Cloning into '/home/runner/work/eventing-kafka/eventing-kafka/src/gopkg.in/src-d/go-billy.v4'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
package gopkg.in/src-d/go-billy.v4: exit status 128
cannot find package "gopkg.in/src-d/go-billy.v4/osfs" in any of:
	/opt/hostedtoolcache/go/1.15.6/x64/src/gopkg.in/src-d/go-billy.v4/osfs (from $GOROOT)
	/home/runner/work/eventing-kafka/eventing-kafka/src/gopkg.in/src-d/go-billy.v4/osfs (from $GOPATH)
cannot find package "gopkg.in/src-d/go-billy.v4/util" in any of:
	/opt/hostedtoolcache/go/1.15.6/x64/src/gopkg.in/src-d/go-billy.v4/util (from $GOROOT)
	/home/runner/work/eventing-kafka/eventing-kafka/src/gopkg.in/src-d/go-billy.v4/util (from $GOPATH)
```

**Comment by pierDipi** [comment]
It seems unrelated.

**Pull request merged**
