### PR TITLE
[0.20] Backport of #509

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Backport #509

### CODE REVIEW

**Review by devguyio — APPROVED** [review]
/lgtm
/approve

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Review by devguyio — CHANGES_REQUESTED** [review]
trying to see if I can get tide unstuck

**Review by devguyio — APPROVED** [review]

**Pull request merged**
