### PR TITLE
[0.22] Updating to Eventing 0.22

### PR DESCRIPTION
**Pull request by matzew**
Similar to https://github.com/knative-sandbox/eventing-kafka/pull/506

Not sure if that should have been merged/done before we create the 0.22 branch for `eventing-kafka`  :thinking: 

Any thoughts @markusthoemmes?

### CODE REVIEW

**Comment by matzew** [comment]
/hold
for clarification

**Comment by markusthoemmes** [comment]
I think it should've, yeah. Wondering if we can make the Releasability action make sure this is all correct? @n3wscott 

/assign @evankanderson

**Comment by lionelvillard** [comment]
I stumbled into this as well during the previous release. IMO, the releasability action is misleading.

**Comment by evankanderson** [comment]
See https://github.com/knative-sandbox/.github/pull/103 for the fix to the releasability check.

**Pull request closed without merging**
