### PR TITLE
[main] KafkaChannel to init offsets before dispatcher 

### PR DESCRIPTION
**Pull request by aliok**
Manual cherry pick of the same fix in 0.24: https://github.com/knative-sandbox/eventing-kafka/pull/886

**Release Note**

```release-note
- 🐛  Fixed a bug that was causing Kafka Channel dispatcher to miss some events in case the offset for the consumer group was not initialized

```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
/hold

let's use :cherries:-pick of the "merge sha" ...

**Comment by aliok** [comment]
> let's use 🍒-pick of the "merge sha" ...

If it works yes, that's nicer.

**Comment by aliok** [comment]
Let's see this one passes the tests then I will cherry pick the changes and do the dance from 0.24 -> ... -> main

**Comment by aliok** [comment]
Ok, let's see what happens to the 0.26 backport: https://github.com/knative-sandbox/eventing-kafka/pull/928

**Comment by aliok** [comment]
/hold

Some renaming to be done here on this PR

**Comment by aliok** [comment]
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-distributed
```
Unable to connect to the server: net/http: TLS handshake timeout
```

**Pull request merged**
