### PR TITLE
Add Immutability Validation

### LINKED ISSUE #862: [KafkaChannel][ResetOffset] Spec Immutability Not Validated
**Describe the bug**
The KafkaChannel and ResetOffset CRD Specs contain inherently immutable settings which are not currently enforced by the WebHook.  If you edit a KafkaChannel or ResetOffset instance and modify the Spec values, it is accepted by Kubernetes but no changes are actually made in the system.  The fields are currently immutable and no changes are expected in the system (working as designed), but for consistency such edits should be rejected.  This will make it clear to the user that the fields are immutable.

 **Expected behavior**
Editing the Spec of a KafkaChannel or ResetOffset should be rejected so that the user understands these fields are immutable post-creation.

 **To Reproduce**
- Edit an existing KafkaChannel and change the `numPartitions`, `replicationFactor` or `retentionDuration` and verify that K8S accepts the change, but that the underlying Kafka Topic was not updated.
- Edit an existing (completed) ResetOffset and change the `offset.time` or `ref.*` and verify that K8S accepts the change, but that no further offset repositioning occurs.

 **Knative release version**
`/main`  ( it has always been this way ; )

 **Additional context**

- It should be noted that the KafkaChannel spec inlines the ChanelableSpec which should not be included in the immutable validation check.
- The immutable KafkaChannel Spec fields are all currently related to Kafka Topic configuration.  It might be a future enhancement to support the ability to change these values, but this current bug is focused on aligning the validation logic with the implementation.

### PR DESCRIPTION
**Pull request by travis-minke-sap**
Fixes #862 

## Proposed Changes
- 🐛  Add immutability checks to the KafkaChannel and ResetOffset Validation.

**Release Note**

```release-note
Inherent immutability of KafkaChannel and ResetOffset spec fields is now enforced by the kafka-webhook.
```

### CODE REVIEW

**Comment by travis-minke-sap** [comment]
holding for @devguyio or @lionelvillard or @matzew etc... to have a look-seee
/hold

**Review by pierDipi — COMMENTED** [review]
/lgtm

Nit: typo in your release notes: kakfa-webhook -> kafka-webhook.

**Comment by travis-minke-sap** [comment]
> /lgtm
> 
> Nit: typo in your release notes: kakfa-webhook -> kafka-webhook.

Thanks Pier - good catch on the typo as well 🤦

**Pull request merged**
