### PR TITLE
Update API versions of HorizontalPodAutoscaler and PodDisruptionBudget

### PR DESCRIPTION
**Pull request by creydr**
The [nightly release job](https://prow.knative.dev/view/gs/knative-prow/logs/nightly_eventing-kafka_main_periodic/1616369505573801984) has some issues with deprecated APIs on upgrade jobs:

```
Jan 20 10:02:44.846 install_released_consolidated_channel [OUT] Applying: /logs/artifacts/channel-consolidated-knative-v1.8.1.yaml
...
Jan 20 10:02:50.925 install_released_consolidated_channel [ERR] Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler
Jan 20 10:02:51.081 install_released_consolidated_channel [OUT] horizontalpodautoscaler.autoscaling/kafka-webhook created
...
Jan 20 10:02:51.298 install_released_consolidated_channel [ERR] error: resource mapping not found for name: "kafka-webhook" namespace: "knative-eventing" from "/logs/artifacts/channel-consolidated-knative-v1.8.1.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
Jan 20 10:02:51.298 install_released_consolidated_channel [ERR] ensure CRDs are installed first
    shell.go:28: exit status 1
```

This PR addresses it and updates the API versions of `HorizontalPodAutoscaler` to `autoscaling/v2` (d70442713eb5e4c7873b89b3903b76ef02041078) and `PodDisruptionBudget` to `policy/v1` (c10f2ff8632bd8761addf65ca8f733b26a824d15).
This will require to backport this PR for a few releases to make the upgrade tests work.

Deprecation guide for 1.25: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

**Release Note**
```release-note
Update HorizontalPodAutoscaler API version to autoscaling/v2
Update PodDisruptionBudget API version to policy/v1
```

### CODE REVIEW

**Comment by aliok** [comment]
@creydr I was working on the same issue... I eventually gave up :)

See https://github.com/knative-sandbox/eventing-kafka/pull/1278

In summary, in previous release, we use `PodDisruptionBudget` v1beta1 and upgrade tests will fail during the installation of the previous version of eventing-kafka.

```
[ERR] error: resource mapping not found for name: "kafka-webhook" namespace: "knative-eventing" from "/logs/artifacts/channel-consolidated-knative-v1.8.1.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

Proper fix would be, fixing PodDisruptionBudget version all the way back to 1.5/1.6.

What we talked in Knative Slack is, that we will remove the KafkaChannel in this repository and problem will be solved as that's the only component using PodDisruptionBudgets.

**Comment by matzew** [comment]
> Proper fix would be, fixing PodDisruptionBudget version all the way back to 1.5/1.6.

yeah, all the way back, or to at least (`main -1`) :smile:

**Comment by pierDipi** [comment]
We can disable the upgrade test for KafkaChannel in this repository

**Pull request merged**
