### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by lionelvillard**
https://github.com/knative-sandbox/eventing-kafka/pull/649 followup.

## Proposed Changes

- remove unused var/struct
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by aliok — APPROVED** [review]
/lgtm
/approve

**Comment by lionelvillard** [comment]
/test pull-knative-sandbox-eventing-kafka-upgrade-tests

this is so painful.

**Pull request merged**
