### PR TITLE
Add KO_FLAGS to e2e test

### PR DESCRIPTION
**Pull request by BbolroC**
This PR is to add a flag `KO_FLAGS` to the e2e test. This opens up a chance to set other KO options (e.g. `--platform`). 

## Proposed Changes

- add KO_FLAGS to `ko apply`

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by pierDipi — APPROVED** [review]
/lgtm
/approve

**Review by pierDipi — APPROVED** [review]

**Comment by BbolroC** [comment]
I have rebased this onto the latest. Please give this `lgtm` again.

**Comment by BbolroC** [comment]
I am working to fix the following error triggered by this PR:

```
install_head_consolidated_source [OUT] test/e2e-common.sh: line 330: KO_FLAGS: unbound variable
```

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
