### PR TITLE
Missing defer close kafka admin client in FinalizeKind

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>

Part of #564

## Proposed Changes

- 🐛 Close the Kafka AdminClient in FinalizeKind

**Release Note**

```release-note
🐛 Close the Kafka AdminClient in FinalizeKind
```

### CODE REVIEW

**Review by devguyio — APPROVED** [review]
Thanks for fixing this!

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
