### PR TITLE
[main] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mgencur**
This replaces https://github.com/knative-sandbox/eventing-kafka/pull/1223 and fixes the linter errors.

## Proposed Changes

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Comment by upodroid** [comment]
@pierDipi 

Copy the serving's codecov file

https://github.com/knative/serving/blob/main/.codecov.yaml

You are at 74% so pick a lower threshold and add more tests in the future.

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
