### PR TITLE
Updates and fixes for slinky's loadastic

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
@slinkydeveloper  I think this is it now... :see_no_evil:

**Comment by slinkydeveloper** [comment]
Seems like you need to run update-codegen

**Comment by matzew** [comment]
> Seems like you need to run update-codegen

well, I did - if really an issue, I think the "build tests" etc would have complained too

**Comment by matzew** [comment]
@slinkydeveloper did it _again_... and... (as expected) -> no diff

so... I think this is OK....

**Comment by slinkydeveloper** [comment]
Sounds like there's a change in the file modes?!

**Comment by matzew** [comment]
yet another round of updates, and a rebase ... lets see ... :sleepy:

**Comment by matzew** [comment]
@slinkydeveloper for some reason, those modes were wrong here .. not sure why.
I changed them, they are now same like on `eventing` core...

also, I did do another round of "updates", to catch the latests (e.g. from today).

I now see that particular one failing check is now :green_heart:

**Comment by slinkydeveloper** [comment]
Thanks!

**Pull request merged**
