### PR TITLE
WIP: Fix KIND

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

Fixes #

## Proposed Changes

- :broom: Adding k8s 1.21
- :wastebasket: drop 1.18 (see https://knative.dev/community/contributing/mechanics/release-versioning-principles/#knative-eventing-version-table)
- :broom:  updates to 1.19 and 1.20 line

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
@matzew you need to update the master -> main branch here https://github.com/knative-sandbox/eventing-kafka/pull/302/files#diff-8d196c4ce9b53dec57fab83c31e0f2a460d671683b19c3ef3d662003e1305d1cL5

**Comment by slinkydeveloper** [comment]
Now it works, failing :smile:

**Comment by matzew** [comment]
> Now it works, failing smile

yep, I think it's related to the different jobs we have (consolidated / distributred / sasl / tls). Looking

**Comment by slinkydeveloper** [comment]
@matzew meanwhile, i guess we can merge it, since it solves the original issue

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

**Comment by slinkydeveloper** [comment]
Is this one still valid?

**Pull request closed without merging**
