### PR TITLE
[release-0.23] Make sure ConsumeClaim exit before rebalance.timeout (#659)

### PR DESCRIPTION
**Pull request by devguyio**
## Proposed Changes

- 🐛 Cancel dispatching messages when consumer group session is closed

**Release Note**

```release-note
- 🐛 Fix a bug in consolidate channel where deleting a KafkaChannel-backed Broker with events in flight blocks new subscriptions in SubscriptionNotMarkedReadyByChannel . 
```

### CODE REVIEW

**Comment by devguyio** [comment]
@googlebot I consent

**Comment by devguyio** [comment]
@lionelvillard can you please give google-bot your consents :)

**Comment by lionelvillard** [comment]
@googlebot I consent

**Pull request merged**
