### PR TITLE
Drop unnecessary pin of go-autorest

### PR DESCRIPTION
**Pull request by markusthoemmes**
## Proposed Changes

Unpin github.com/Azure/go-autorest. The pin seems arbitrary, the version is old and stuff fails in pkg's CI: https://github.com/knative/pkg/pull/1819/checks?check_run_id=1274282107

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
/assign @travis-minke-sap 

Why we have this pin?

**Comment by slinkydeveloper** [comment]
@markusthoemmes can you rebase? this should be fixed in master

**Comment by markusthoemmes** [comment]
Done.

**Pull request merged**
