### PR TITLE
move eventing/pkg/apis/duck/v1alpha1 here

### PR DESCRIPTION
**Pull request by vaikas**
Addresses #426 

## Proposed Changes

- This moves the ducks from knative.dev/eventing/pkg/apis/duck/v1alpha1 here

**Release Note**

```release-note
 * Note that after the upstream PR: https://github.com/knative/eventing/pull/5005 goes in, old v1alpha1 channels will not be reconciled.

```

**Docs**

### CODE REVIEW

**Comment by vaikas** [comment]
So, as expected the v1alpha1 tests are now failing.

**Comment by pierDipi** [comment]
I can't think of any other solution.

I guess during a "pre-upgrade step" we have to:
- change the stored version to v1beta1 
- stop serving v1alpha1

_and there no way to downgrade_

Such pre-upgrade has to happen before upgrading eventing.

/cc @matzew @travis-minke-sap

**Comment by pierDipi** [comment]
In this PR we should remove v1alpha1.

**Comment by vaikas** [comment]
@pierDipi would you like me to make the PR that removes the v1alpha1 as part of this PR? If that's the case, upgrade will not be easily done (not even sure how) since the storage upgrade scripts reads them in at v1alpha1 and converts. I could stop serving v1alpha1 if that's what you'd like. But I think I personally would split the PRs into this, then the next and upgrade separate ones for smaller chunks. Thoughts?

**Comment by pierDipi** [comment]
If you can make tests work in smaller chunks, I prefer smaller chunks, but at this point I guess v1alpha1 with the latest eventing just doesn't work, that's the reason I was suggesting to remove it, or am I wrong?

For the upgrade part, I'm thinking to a multi step pre-upgrade with multiple jobs, or do you a better solution to give users an upgrade path?

**Comment by vaikas** [comment]
@pierDipi ok, I disabled tests with v1alpha1 and everything passes. So, I think we should get this in, and start working on the upgrade path, thoughts?

**Review by travis-minke-sap — APPROVED** [review]
looks like a good stepping stone ; )

**Pull request merged**
