### PR TITLE
use default autocommit configuration

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

- Offsets are now committed to the broker
-
-

**Release Note**

```release-note
🐛 Offsets are now committed to the broker using the autocommit policy (default flush interval is 1s)
```

**Docs**

### CODE REVIEW

**Comment by matzew** [comment]
LOL:

```
error: unable to read URL "https://storage.googleapis.com/knative-nightly/serving/latest/monitoring.yaml", server reported 404 Not Found, status code=404
ERROR: Knative setup failed
```

**Comment by lionelvillard** [comment]
@matzew can we merge this one? (the lint error is fixed in another PR)

**Comment by devguyio** [comment]
@lionelvillard was the KafkaSource not doing any explicit commit before and hence you wanted to enable auto commit?

**Comment by lionelvillard** [comment]
@devguyio that's right. Auto commit sounds like a good default policy. Eventually there should be a way to specify a different policy (see https://github.com/knative-sandbox/eventing-kafka/issues/108).

**Comment by matzew** [comment]
/lgtm
/approve

/hold 

@pierDipi or @slinkydeveloper  wanna give a thought ?

**Review by pierDipi — APPROVED** [review]
/lgtm

**Pull request merged**
