### PR TITLE
Use PodDisruptionBudget v1

### PR DESCRIPTION
**Pull request by aliok**
Fixes #

## Proposed Changes

- Use PodDisruptionBudget v1
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Comment by aliok** [comment]
During upgrade tests, installing the previous version fails because of inexistent PodDisruptionBudget in policy/v1beta1.

**Review by matzew — APPROVED** [review]
/lgtm
/apporve

**Comment by matzew** [comment]
> During upgrade tests, installing the previous version fails because of inexistent PodDisruptionBudget in policy/v1beta1.

I'd assume that the CI for the previous job is also on the same k8s version as this one? If so, hard to address.
Unless we go all the way back (assuming older versions of our software run on older k8s versions where this actually fits).

That said, but I am not sure really worth it, see:  https://github.com/knative-sandbox/eventing-kafka/pull/1259

**Comment by aliok** [comment]
/close 

Context: https://knative.slack.com/archives/C02C56QF282/p1672925909239859

**Pull request closed without merging**
