### PR TITLE
disable control server when running the mt source.

### PR DESCRIPTION
**Pull request by lionelvillard**
## Proposed Changes

- Temporarily disable the source control server when runnning within the mt source adapter
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

**Review by slinkydeveloper — COMMENTED** [review]
Don't you need changes in the controller too?

**Comment by lionelvillard** [comment]
> Don't you need changes in the controller too?

there are 2 controllers, one for the single-tenant and another one for the multi-tenant. So I hope not

**Comment by lionelvillard** [comment]
first attempt failed. ...

**Comment by lionelvillard** [comment]
ok fixed!

@aliok @slinkydeveloper @matzew  I need a stamp! thanks :-)

**Review by slinkydeveloper — APPROVED** [review]
/lgtm

**Review by matzew — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
